edition = "2024"
style_edition = "2024"
unstable_features = true
format_strings = true

# wrap_comments = true
# format_code_in_doc_comments = true
# group_imports = "StdExternalCrate"
# imports_granularity = "Crate"
